
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" vim options
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set nocompatible

set autoindent
set autoread
set backspace=indent,eol,start
set cindent
set clipboard=unnamedplus
set cmdheight=2
set encoding=utf-8
set expandtab
set gp=git\ grep\ -n
set hidden
set hlsearch
set ignorecase
set incsearch
set mouse=a
set noerrorbells visualbell t_vb=
set nobackup
set noswapfile
set noundofile
set nowrap
set number
set ruler
set shell=/bin/bash
"set shell=cmd.exe
set shiftwidth=4
set showcmd
set smartcase
set smarttab
set softtabstop=4
set splitbelow
set splitright
set t_vb=
set tabstop=4
set tags=./tags,tags
set timeout timeoutlen=500 ttimeoutlen=10
set wildignore+='*/tmp/*,*/target/*,*/bin/*,*/build/*,*/__pycache__/*,*.tar,*.gz,*.7z,*.iso,*.so,*.swp,*.zip'
set wildmenu
set wildmode=list:longest,full

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" gui options (gvim, macvim)
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"set guifont=Hack:h18 " Font
set guioptions-=m    " Menubar
set guioptions-=T    " Toolbar
set guioptions-=r    " Scrollbar

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" statusline
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set laststatus=3                             " Show status bar
set statusline=                              " Clear the statusline for when vimrc is reloaded
set statusline+=\ %-3.3n\                    " Buffer number
set statusline+=%f\                          " File name
set statusline+=%h%m%r%w                     " Flags
set statusline+=[%{strlen(&ft)?&ft:'none'},  " Filetype
set statusline+=%{strlen(&fenc)?&fenc:&enc}, " Encoding
set statusline+=%{&fileformat}]              " File format
set statusline+=%=                           " Right align
set statusline+=%c,                          " Cursor column
set statusline+=%l/%L\                       " Cursor line/total lines

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" package settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

packadd! cfilter
packadd! comment
packadd! editorconfig
packadd! hlyank
packadd! matchit
packadd! nohlsearch
packadd! osc52
packadd! termdebug

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" plugins
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Vim-Plug
call plug#begin()

" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
"   - Neovim (Linux/macOS/Windows): stdpath('data') . '/plugged'

" Make sure you use single quotes
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'derekwyatt/vim-fswitch'
Plug 'airblade/vim-rooter'
Plug 'yegappan/lsp'

" Initialize plugin system
" Automatically executes `filetype plugin indent on` and `syntax enable`.
call plug#end()

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" plugin settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" fzf
let g:fzf_vim = {}
let g:fzf_vim.preview_bash = '/bin/bash'
"let g:fzf_vim.preview_bash = 'C:\Program Files\Git\bin\bash.exe'
let g:fzf_vim.buffers_jump = 1
let g:fzf_vim.commits_log_options = '--graph --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr"'
let g:fzf_vim.tags_command = 'ctags -R'

" fzf - the silver searcher
let g:ackprg = 'ag --vimgrep'

" vim-rooter - remove: set autochdir
let g:rooter_patterns = ['.git', 'CMakeLists.txt', 'Makefile', 'pom.xml']

" lsp
let s:lspServers = [
    \ #{ name: 'clangd', filetype: ['c', 'cpp'], path: 'clangd', args: ['--background-index'] },
    \ ]

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" custom variables
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let $RIPGREP_CONFIG_PATH = expand('~/.config/ripgrep/ripgreprc')

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" custom functions
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

function! SetMarkAtCurrentLine()
    let l:letters = 'abcdefghijklmnopqrstuvwxyz'
    let l:current_line = line('.')
    " check if the current line already has a mark
    for l:letter in split(l:letters, '\zs')
        if getpos("'" . l:letter)[1] == l:current_line
            echo "Mark " . l:letter . " already set at line " . l:current_line 
            return
        endif
    endfor
    " find an unused mark
    for l:letter in split(l:letters, '\zs')
        if getpos("'" . l:letter)[1] == 0  " mark is unused if line == 0
            execute "mark " . l:letter
            echo "Mark " . l:letter . " set at line " . l:current_line 
            return
        endif
    endfor
    echo "No unused marks available"
endfunction

function! s:on_lsp_buffer_enabled() abort
    setlocal tagfunc=lsp#lsp#TagFunc
    " navigation
    nnoremap <buffer> <silent> gf :LspGotoDefinition<CR>
    nnoremap <buffer> <silent> gd :LspGotoDeclaration<CR>
    nnoremap <buffer> <silent> gb :LspGotoImpl<CR>
    nnoremap <buffer> <silent> gt :LspGotoTypeDef<CR>
    nnoremap <buffer> <silent> gr :LspShowReferences<CR>
    " peek (popup, cursor stays)
    nnoremap <buffer> <silent> gp :LspPeekDefinition<CR>
    " info
    nnoremap <buffer> <silent> K  :LspHover<CR>
    nnoremap <buffer> <silent> <leader>k :LspShowSignature<CR>
    " symbols / structure
    nnoremap <buffer> <silent> <F12> :LspDocumentSymbol<CR>
    nnoremap <buffer> <silent> <leader>m :LspSymbolSearch<CR>
    nnoremap <buffer> <silent> <leader>ci :LspIncomingCalls<CR>
    nnoremap <buffer> <silent> <leader>co :LspOutgoingCalls<CR>
    " refactor / edit
    nnoremap <buffer> <silent> <leader>rr :LspRename<CR>
    nnoremap <buffer> <silent> <leader>F :LspFormat<CR>
    xnoremap <buffer> <silent> <leader>v :LspSelectionExpand<CR>
endfunction

" ---- termdebug (gdb) key mappings ----
" F5 starts a session (build debug + launch on this project's binary).
" All other debug keys are installed ONLY while a session is active and
" reverted to their normal editing meaning when the session ends.

function! s:DebugLayout() abort
    let l:gdbwin = bufwinid('gdb')
    let l:prgwin = bufwinid('debugged-program')
    " console to full-width bottom
    if l:prgwin != -1
        call win_gotoid(l:prgwin)
        wincmd J
    endif
    " gdb to the right of source
    if l:gdbwin != -1
        call win_gotoid(l:gdbwin)
        wincmd L
    endif
    " focus back to source
    if exists('g:debug_return_win')
        call win_gotoid(g:debug_return_win)
    endif
endfunction

" F5: build debug binary, then launch termdebug on this project's target
function! s:DebugStart() abort
    let g:debug_return_win = win_getid()
    silent make debug
    execute 'Termdebug ./' . trim(system('make print-target'))
endfunction

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" custom automation
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" NASM x86-64
autocmd BufRead,BufNewFile *.asm set filetype=nasm
autocmd FileType nasm setlocal noexpandtab
autocmd FileType nasm setlocal commentstring=;\ %s

" C/C++
autocmd FileType c,cpp setlocal commentstring=//\ %s
autocmd FileType c,cpp setlocal errorformat=%f:%l:%c:\ %t%*[^:]:\ %m,%f:%l:\ %t%*[^:]:\ %m,%-G%.%#
autocmd FileType c,cpp setlocal makeprg=make

" Java
autocmd FileType java setlocal commentstring=//\ %s
autocmd FileType java setlocal errorformat=[ERROR]\ %f:[%l\,%c]\ %m,%-G%.%#
autocmd FileType java setlocal makeprg=mvn\ -q\ compile

" Do not list .cache in buffers
autocmd BufReadPost,BufNewFile */.cache/* setlocal nobuflisted

augroup VimStartup
    au!
    au GUIEnter * set visualbell t_vb=
augroup END

autocmd User LspSetup call LspAddServer(s:lspServers)

augroup lsp_buffer
    au!
    autocmd User LspAttached call s:on_lsp_buffer_enabled()
augroup END

" terminal buffers wipe when their window closes - leaves no dead buffers
autocmd TerminalOpen * setlocal bufhidden=wipe

augroup TermdebugMaps
    au!
    autocmd User TermdebugStartPost call s:DebugMapsOn()
    autocmd User TermdebugStopPost  call s:DebugMapsOff()
augroup END


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" custom settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" set default working directory
cd $HOME/Workspace
"cd 'C:\Users\username\Workspace'

" set default colorscheme
silent! colorscheme industry
syntax on

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" custom key mappings
"'""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" quick ex mode
noremap ; :

" move into wrapped lines
nnoremap j gj
nnoremap k gk

" configure command leader
let mapleader=","

" go to last edit location 
nnoremap <leader>. g;

" go to last edit location in insert mode 
nnoremap <leader>; gi

" browse files
nnoremap <leader>E :Ex<CR>

" list buffers
nnoremap <leader>b :ls<CR>
nnoremap <leader>e :Buffers<CR>

" show commits
nnoremap <leader>C :Commits<CR>

" file search
nnoremap <leader>f :Files<CR>

" find/grep in current file if opened or in all files
nnoremap <leader>g :Rg<CR>

" project file search
nnoremap <leader>t :GFiles<CR>

" duplicate current line
nnoremap <leader>d Yp

" indent whole file
nnoremap <leader>L maggVG='a

" close current buffer
nnoremap <leader>q :bd<CR>

" prepare for searc h/replace on the whole file
nnoremap <leader>R :%s/

" prepare for search/replace on the current line
nnoremap <leader>r V:s/

" prepare incremental search forward 
nnoremap <leader>j :/

" save / overwrite
nnoremap <leader>s :w!<CR>

" switch buffers
nnoremap <silent> H :bp<CR>
nnoremap <silent> L :bn<CR> 

" cycle windows
nnoremap <leader>w <C-w>w

" close all other windows (keep current)
nnoremap <silent> <leader><space> :only<CR>

" view help
nnoremap <F1> :Help<CR>

" fuzzy jump search in current file
nnoremap <F3> :BLines<CR>

" go to next mark in current buffer
nnoremap <F2> ]`

" go to previous mark in current buffer
nnoremap <S-F2> [`

" delete current buffer
nnoremap <F4> :bd<CR>

" start debug session
nnoremap <silent> <S-F5> :call <SID>DebugStart()<CR>

" view changed files history
nnoremap <F6> :History<CR>

" build
nnoremap <F7> :make<CR>

" clean build
nnoremap <S-F7> :make clean all<CR>

" clean build and run in a terminal buffer
nnoremap <A-F7> :make clean all<CR>:terminal make run<CR>

" jump to first LSP error
nnoremap <A-F8> :LspDiag first<CR>

" jump to next LSP error
nnoremap <F8> :LspDiag next<CR>

" jump to previous LSP error
nnoremap <S-F8> :LspDiag prev<CR>

" open quickfix window
nnoremap <A-F9> :cw<CR>

" jump to next compiler error
nnoremap <F9> :cn<CR>

" jump to previous compiler error
nnoremap <S-F9> :cp<CR>

" reload current file / undo all changes
nnoremap <A-F12> :e!<CR>

" show header file in right vertical-split
nnoremap <silent> <leader>a :FSSplitRight<CR>

" set random mark at current buffer line
nnoremap <leader>mm :call SetMarkAtCurrentLine()<CR>

" show marks
nnoremap <leader>ml :Marks<CR>

" delete all marks
nnoremap <leader>mr :delmarks!<CR>:delmark A-Z<CR>:echo "All marks deleted"<CR>

" installed when a debug session starts
function! s:DebugMapsOn() abort
    nnoremap <silent> <F5>    :Run<CR>
    nnoremap <silent> <F8>    :Break<CR>
    nnoremap <silent> <S-F8>  :Clear<CR>
    nnoremap <silent> <F9>    :Over<CR>
    nnoremap <silent> <F10>   :Step<CR>
    nnoremap <silent> <S-F10> :Finish<CR>
    nnoremap <silent> <F11>   :Continue<CR>
    nnoremap <silent> <S-F11> :call TermDebugSendCommand('quit')<CR>
    nnoremap <silent> <S-F12> :Asm<CR>
    call s:DebugLayout()
endfunction

" restored when the debug session ends
function! s:DebugMapsOff() abort
    nnoremap <silent> <F8>   :LspDiag next<CR>
    nnoremap <silent> <S-F8> :LspDiag prev<CR>
    nnoremap <silent> <F9>   :cn<CR>
    nnoremap <silent> <S-F9> :cp<CR>
    silent! nunmap <F5>
    silent! nunmap <F10>
    silent! nunmap <S-F10>
    silent! nunmap <F11>
    silent! nunmap <S-F11>
    silent! nunmap <S-F12>
endfunction

