@echo off
doskey b=git branch -avv
doskey c=cls
doskey d=cd /D %USERPROFILE%\Desktop
doskey dbg=remedybg $*
doskey e=explorer $*
doskey f=subl $*
doskey g=git status
doskey gg=git ls $*
doskey gca=git add . $T git commit --amend --no-edit
doskey gcapf=git add . $T git commit --amend --no-edit $T git push -f
doskey gd=git diff 
doskey gdc=git diff --cached
doskey h=cd /D %USERPROFILE%
doskey hexdump=powershell Format-Hex $*
doskey k=kubectl
doskey l=powershell ls -Force $*
doskey pe=procexp64
doskey pipenv=python -m pipenv $*
doskey r=cd \
doskey touch=powershell New-Item $* -ItemType file
doskey venv=python -m venv .venv
doskey vc=python -m venv .venv
doskey va=.venv\Scripts\activate
doskey vd=.venv\Scripts\deactivate
doskey vr=rd /s /q .venv
doskey vim=start /b "" "C:\Program Files\Vim\vim82\gvim.exe" $*
doskey w=cd /D D:\Workspace
doskey windbg="C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\windbg.exe" $*
