@ECHO OFF
SETLOCAL
CALL uvars.bat || EXIT /B
FOR %%i IN ("%CD%") DO SET "PROJECT=%%~ni"
SET UBUILD=%UE_PROJECTS_HOME%\Build.bat
SET UOPEN=%UE_PROJECTS_HOME%\Open.bat
CALL %UBUILD% %PROJECT% && %UOPEN% %PROJECT%

