
# Global
export PATH="$HOME/.local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"

# Bash
export TERM="xterm-256color"
export PS1=" \w $ "
export BASH_SILENCE_DEPRECATION_WARNING=1
export BASH="/opt/homebrew/bin/bash"
export EDITOR="vim"
export SHELL="$BASH"

# Brew
export BREW_HOME="/opt/homebrew"
export PATH="$BREW_HOME/bin:$PATH"
export HOMEBREW_EDITOR="vim"
export PATH="$HOMEBREW_EDITOR/bin:$PATH"

# FZF
export FZF_DEFAULT_COMMAND="fd --type f --follow"
export FZF_DEFAULT_OPTS="--border --inline-info"

# GPG
export GPG_TTY=$(tty)

# Python
export PYTHONBREAKPOINT=0
export PYTHONBREAKPOINT=pudb.set_trace

# Pipenv
export PIPENV_LOCAL="/Users/$USER/.local"
export PATH="$PIPENV_LOCAL/bin:$PATH"
export PIPENV_VENV_IN_PROJECT=1

# Aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Execute on startup
source "$HOME/.sdkman/bin/sdkman-init.sh"
